directory:
- .
download-external-modules: false
evaluate-variables: true
external-modules-download-path: .external_modules
framework: all
skip-check:
- CKV_AWS_92  #Ensure the ELB has access logging enabled. For the minimal example, this is not enabled
- CKV_AWS_144 #Ensure that S3 bucket has cross-region replication enabled
- CKV_AWS_18  #Ensure the S3 bucket has access logging enabled
- CKV_AWS_145 #Ensure that S3 buckets are encrypted with KMS by default:: We are using the default `aws/s3`. This can be overwriten by providing the value of `access_logs_kms_id`
- CKV2_AWS_61 #"Ensure that an S3 bucket has a lifecycle configuration"
- CKV2_AWS_62 #"Ensure S3 buckets should have event notifications enabled"
- CKV2_AWS_6 #"Ensure that S3 bucket has a Public Access block"
- CKV_AWS_21 #"Ensure all data stored in the S3 bucket have versioning enabled"
