directory:
- .
download-external-modules: false
evaluate-variables: true
external-modules-download-path: .external_modules
framework: all
skip-check:
- CKV_AWS_92  #Ensure the ELB has access logging enabled. For the minimal example, this is not enabled
- CKV_AWS_144 #Ensure that S3 bucket has cross-region replication enabled
- CKV_AWS_18  #Ensure the S3 bucket has access logging enabled
