variable "name" {
  type        = string
  description = "(Optional) The name of the ELB. By default generated by Terraform."
  default     = null
}

variable "name_prefix" {
  type        = string
  description = "(Optional, Forces new resource) Creates a unique name beginning with the specified prefix. Conflicts with `name`"
  default     = null
}

variable "access_logs" {
  type        = map(string)
  description = "(Optional) An Access Logs block."
  default     = {}
}

variable "availability_zones" {
  type        = list(string)
  description = "(Required for an EC2-classic ELB) The AZ's to serve traffic in."
  default     = []
}

variable "security_groups" {
  type        = list(string)
  description = "(Optional) A list of security group IDs to assign to the ELB. Only valid if creating an ELB within a VPC"
  default     = []
}

variable "subnets" {
  type        = list(string)
  description = "(Required for a VPC ELB) A list of subnet IDs to attach to the ELB."
  default     = []
}

variable "instances" {
  type        = list(string)
  description = "(Optional) A list of instance ids to place in the ELB pool."
  default     = []
}

variable "internal" {
  type        = bool
  description = "(Optional) If true, ELB will be an internal ELB."
  default     = false
}

variable "listener" {
  type        = map(string)
  description = "(Required) A list of listener blocks."
  default     = {}
}

variable "health_check" {
  type        = map(string)
  description = "(Optional) A health_check block."
  default     = {}
}

variable "cross_zone_load_balancing" {
  type        = bool
  description = "(Optional) Enable cross-zone load balancing."
  default     = true
}

variable "idle_timeout" {
  type        = number
  description = "(Optional) The time in seconds that the connection is allowed to be idle. Default: `60`"
  default     = 60
}

variable "connection_draining" {
  type        = bool
  description = "(Optional) Boolean to enable connection draining. Default: `false`"
  default     = false
}

variable "connection_draining_timeout" {
  type        = number
  description = "(Optional) The time in seconds to allow for connections to drain. Default: `300`"
  default     = 300
}

variable "desync_mitigation_mode" {
  type        = string
  description = "(Optional) Determines how the load balancer handles requests that might pose a security risk to an application due to HTTP desync. Valid values are `monitor`, `defensive` (default), `strictest`."
  default     = "defensive"
}

variable "tags" {
  type        = map(string)
  description = "(Optional) A map of tags to assign to the resource."
  default     = {}
}

variable "policy_name" {
  type        = string
  description = "(Required) The name of the load balancer policy."
  default     = null
}

variable "policy_type_name" {
  type        = string
  description = "(Required) The policy type."
  default     = null
}

variable "loadbalancer_policy_attribute" {
  type        = map(string)
  description = "(Optional) Policy attribute to apply to the policy."
  default     = {}
}

variable "create_access_logs_bucket" {
  type        = bool
  description = "Specify whether to create access logs bucket"
  default     = false
}
