variable "name" {
  type        = string
  description = "(Optional) The name of the ELB. By default generated by Terraform."
  default     = null
}

variable "name_prefix" {
  type        = string
  description = "(Optional, Forces new resource) Creates a unique name beginning with the specified prefix. Conflicts with `name`"
  default     = null
}

variable "access_logs" {
  type        = map(string)
  description = "(Optional) An Access Logs block."
  default     = {}
}

variable "availability_zones" {
  type        = list(string)
  description = "(Required for an EC2-classic ELB) The AZ's to serve traffic in."
  default     = []
}

variable "security_groups" {
  type        = list(string)
  description = "(Optional) A list of security group IDs to assign to the ELB. Only valid if creating an ELB within a VPC"
  default     = []
}

variable "subnets" {
  type        = list(string)
  description = "(Required for a VPC ELB) A list of subnet IDs to attach to the ELB."
  default     = []
}

variable "instances" {
  type        = list(string)
  description = "(Optional) A list of instance ids to place in the ELB pool."
  default     = []
}

variable "internal" {
  type        = bool
  description = "(Optional) If true, ELB will be an internal ELB."
  default     = false
}

variable "access_logs_kms_id" {
  type        = string
  description = "The AWS KMS master key ID used for the SSE-KMS encryption. This can only be used when you set the value of access_logs_sse_algorithm as `aws:kms`."
  default     = false
}

variable "access_logs_sse_algorithm" {
  type        = string
  description = "The server-side encryption algorithm to use for the elb access logs bucket. Valid values are `AES256` and `aws:kms`"
  default     = "AES256"
}

variable "listeners" {
  type        = list(any)
  description = "(Required) A list of listener blocks."
  default     = []
}

variable "health_check" {
  type        = map(string)
  description = "(Optional) A health_check block."
  default     = {}
}

variable "elb_additional_s3_policy" {
  type        = any
  description = "Provide additional custom policy for ELB access to S3 bucket created in the module."
  default     = []
}

variable "cross_zone_load_balancing" {
  type        = bool
  description = "(Optional) Enable cross-zone load balancing."
  default     = true
}

variable "idle_timeout" {
  type        = number
  description = "(Optional) The time in seconds that the connection is allowed to be idle. Default: `60`"
  default     = 60
}

variable "connection_draining" {
  type        = bool
  description = "(Optional) Boolean to enable connection draining. Default: `false`"
  default     = false
}

variable "connection_draining_timeout" {
  type        = number
  description = "(Optional) The time in seconds to allow for connections to drain. Default: `300`"
  default     = 300
}

variable "desync_mitigation_mode" {
  type        = string
  description = "(Optional) Determines how the load balancer handles requests that might pose a security risk to an application due to HTTP desync. Valid values are `monitor`, `defensive` (default), `strictest`."
  default     = "defensive"
}

variable "tags" {
  type        = map(string)
  description = "(Optional) A map of tags to assign to the resource."
  default     = {}
}

variable "load_balancer_policies" {
  type        = any
  description = "Load balancer policy resource block for single or multiple resources"
  default     = {}
}

variable "create_access_logs_bucket" {
  type        = bool
  description = "Specify whether to create access logs bucket"
  default     = false
}
